package exportkit.id;

import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

public class homescreen_activity extends Activity {

	
	private View _bg__homescreen_ek2;
	private ImageView vector;
	private ImageView vector_ek1;
	private ImageView vector_ek2;
	private ImageView vector_ek3;
	private ImageView vector_ek4;
	private ImageView vector_ek5;
	private ImageView vector_ek6;
	private ImageView vector_ek7;
	private ImageView vector_ek8;
	private ImageView vector_ek9;
	private ImageView vector_ek10;
	private ImageView vector_ek11;
	private ImageView vector_ek12;
	private ImageView vector_ek13;
	private ImageView vector_ek14;
	private ImageView vector_ek15;
	private ImageView vector_ek16;
	private ImageView vector_ek17;
	private ImageView vector_ek18;
	private ImageView vector_ek19;
	private ImageView vector_ek20;
	private ImageView vector_ek21;
	private ImageView vector_ek22;
	private ImageView vector_ek23;
	private ImageView vector_ek24;
	private ImageView vector_ek25;
	private ImageView vector_ek26;
	private ImageView vector_ek27;
	private ImageView vector_ek28;
	private ImageView vector_ek29;
	private ImageView vector_ek30;
	private ImageView vector_ek31;
	private ImageView vector_ek32;
	private ImageView vector_ek33;
	private ImageView vector_ek34;
	private ImageView vector_ek35;
	private ImageView vector_ek36;
	private ImageView vector_ek37;
	private ImageView vector_ek38;
	private ImageView vector_ek39;
	private ImageView vector_ek40;
	private ImageView vector_ek41;
	private ImageView vector_ek42;
	private ImageView vector_ek43;
	private ImageView vector_ek44;
	private ImageView vector_ek45;
	private ImageView vector_ek46;
	private ImageView vector_ek47;
	private ImageView vector_ek48;
	private ImageView vector_ek49;
	private ImageView vector_ek50;
	private ImageView vector_ek51;
	private ImageView vector_ek52;
	private ImageView vector_ek53;
	private ImageView vector_ek54;
	private ImageView vector_ek55;
	private ImageView vector_ek56;
	private ImageView vector_ek57;
	private ImageView vector_ek58;
	private ImageView vector_ek59;
	private ImageView vector_ek60;
	private ImageView vector_ek61;
	private ImageView vector_ek62;
	private ImageView vector_ek63;
	private ImageView vector_ek64;
	private ImageView vector_ek65;
	private ImageView vector_ek66;
	private ImageView vector_ek67;
	private ImageView vector_ek68;
	private ImageView vector_ek69;
	private ImageView vector_ek70;
	private ImageView vector_ek71;
	private ImageView vector_ek72;
	private ImageView vector_ek73;
	private ImageView vector_ek74;
	private ImageView vector_ek75;
	private ImageView vector_ek76;
	private ImageView vector_ek77;
	private ImageView vector_ek78;
	private ImageView vector_ek79;
	private ImageView vector_ek80;
	private ImageView vector_ek81;
	private ImageView vector_ek82;
	private ImageView vector_ek83;
	private ImageView vector_ek84;
	private ImageView vector_ek85;
	private ImageView vector_ek86;
	private ImageView vector_ek87;
	private ImageView vector_ek88;
	private ImageView vector_ek89;
	private ImageView vector_ek90;
	private ImageView vector_ek91;
	private ImageView vector_ek92;
	private ImageView vector_ek93;
	private ImageView vector_ek94;
	private ImageView vector_ek95;
	private ImageView vector_ek96;
	private ImageView vector_ek97;
	private ImageView vector_ek98;
	private ImageView vector_ek99;
	private View rectangle_5;
	private ImageView no_color_1;
	private TextView selamat_datang__indira_;
	private TextView f_o_o_d_n_e_w_s;
	private View line_1;
	private View line_2;
	private View ellipse_6;
	private ImageView chadfarrel_1;
	private TextView berita_harian_anda_tentang_makanan;
	private View news;
	private ImageView _5_sehat_1;
	private View rectangle_16;
	private TextView pertajam_kemampuan_otak_dengan_konsumsi_5_makanan_ini_setiap_hari;
	private View news_ek1;
	private ImageView pisang_1;
	private View rectangle_16_ek1;
	private TextView _5_makanan_sehat_yang_timbulkan_efek_samping_jika_dikonsumsi_berlebihan;
	private View news_ek2;
	private ImageView kantuk_1;
	private View rectangle_16_ek2;
	private TextView trik_agar_tidak_kantuk_usai_makan_siang;
	private View news_ek3;
	private ImageView fermentasi_1;
	private View rectangle_16_ek3;
	private TextView trik_agar_tidak_kantuk_usai_makan_siang_ek1;
	private View rectangle_1;
	private ImageView vector_ek100;
	private ImageView vector_ek101;
	private ImageView vector_ek102;
	private ImageView vector_ek103;
	private ImageView vector_ek104;
	private ImageView vector_ek105;
	private ImageView vector_ek106;
	private ImageView vector_ek107;
	private TextView home_ek1;

	@Override
	public void onCreate(Bundle savedInstanceState) {

		super.onCreate(savedInstanceState);
		setContentView(R.layout.homescreen);

		
		_bg__homescreen_ek2 = (View) findViewById(R.id._bg__homescreen_ek2);
		vector = (ImageView) findViewById(R.id.vector);
		vector_ek1 = (ImageView) findViewById(R.id.vector_ek1);
		vector_ek2 = (ImageView) findViewById(R.id.vector_ek2);
		vector_ek3 = (ImageView) findViewById(R.id.vector_ek3);
		vector_ek4 = (ImageView) findViewById(R.id.vector_ek4);
		vector_ek5 = (ImageView) findViewById(R.id.vector_ek5);
		vector_ek6 = (ImageView) findViewById(R.id.vector_ek6);
		vector_ek7 = (ImageView) findViewById(R.id.vector_ek7);
		vector_ek8 = (ImageView) findViewById(R.id.vector_ek8);
		vector_ek9 = (ImageView) findViewById(R.id.vector_ek9);
		vector_ek10 = (ImageView) findViewById(R.id.vector_ek10);
		vector_ek11 = (ImageView) findViewById(R.id.vector_ek11);
		vector_ek12 = (ImageView) findViewById(R.id.vector_ek12);
		vector_ek13 = (ImageView) findViewById(R.id.vector_ek13);
		vector_ek14 = (ImageView) findViewById(R.id.vector_ek14);
		vector_ek15 = (ImageView) findViewById(R.id.vector_ek15);
		vector_ek16 = (ImageView) findViewById(R.id.vector_ek16);
		vector_ek17 = (ImageView) findViewById(R.id.vector_ek17);
		vector_ek18 = (ImageView) findViewById(R.id.vector_ek18);
		vector_ek19 = (ImageView) findViewById(R.id.vector_ek19);
		vector_ek20 = (ImageView) findViewById(R.id.vector_ek20);
		vector_ek21 = (ImageView) findViewById(R.id.vector_ek21);
		vector_ek22 = (ImageView) findViewById(R.id.vector_ek22);
		vector_ek23 = (ImageView) findViewById(R.id.vector_ek23);
		vector_ek24 = (ImageView) findViewById(R.id.vector_ek24);
		vector_ek25 = (ImageView) findViewById(R.id.vector_ek25);
		vector_ek26 = (ImageView) findViewById(R.id.vector_ek26);
		vector_ek27 = (ImageView) findViewById(R.id.vector_ek27);
		vector_ek28 = (ImageView) findViewById(R.id.vector_ek28);
		vector_ek29 = (ImageView) findViewById(R.id.vector_ek29);
		vector_ek30 = (ImageView) findViewById(R.id.vector_ek30);
		vector_ek31 = (ImageView) findViewById(R.id.vector_ek31);
		vector_ek32 = (ImageView) findViewById(R.id.vector_ek32);
		vector_ek33 = (ImageView) findViewById(R.id.vector_ek33);
		vector_ek34 = (ImageView) findViewById(R.id.vector_ek34);
		vector_ek35 = (ImageView) findViewById(R.id.vector_ek35);
		vector_ek36 = (ImageView) findViewById(R.id.vector_ek36);
		vector_ek37 = (ImageView) findViewById(R.id.vector_ek37);
		vector_ek38 = (ImageView) findViewById(R.id.vector_ek38);
		vector_ek39 = (ImageView) findViewById(R.id.vector_ek39);
		vector_ek40 = (ImageView) findViewById(R.id.vector_ek40);
		vector_ek41 = (ImageView) findViewById(R.id.vector_ek41);
		vector_ek42 = (ImageView) findViewById(R.id.vector_ek42);
		vector_ek43 = (ImageView) findViewById(R.id.vector_ek43);
		vector_ek44 = (ImageView) findViewById(R.id.vector_ek44);
		vector_ek45 = (ImageView) findViewById(R.id.vector_ek45);
		vector_ek46 = (ImageView) findViewById(R.id.vector_ek46);
		vector_ek47 = (ImageView) findViewById(R.id.vector_ek47);
		vector_ek48 = (ImageView) findViewById(R.id.vector_ek48);
		vector_ek49 = (ImageView) findViewById(R.id.vector_ek49);
		vector_ek50 = (ImageView) findViewById(R.id.vector_ek50);
		vector_ek51 = (ImageView) findViewById(R.id.vector_ek51);
		vector_ek52 = (ImageView) findViewById(R.id.vector_ek52);
		vector_ek53 = (ImageView) findViewById(R.id.vector_ek53);
		vector_ek54 = (ImageView) findViewById(R.id.vector_ek54);
		vector_ek55 = (ImageView) findViewById(R.id.vector_ek55);
		vector_ek56 = (ImageView) findViewById(R.id.vector_ek56);
		vector_ek57 = (ImageView) findViewById(R.id.vector_ek57);
		vector_ek58 = (ImageView) findViewById(R.id.vector_ek58);
		vector_ek59 = (ImageView) findViewById(R.id.vector_ek59);
		vector_ek60 = (ImageView) findViewById(R.id.vector_ek60);
		vector_ek61 = (ImageView) findViewById(R.id.vector_ek61);
		vector_ek62 = (ImageView) findViewById(R.id.vector_ek62);
		vector_ek63 = (ImageView) findViewById(R.id.vector_ek63);
		vector_ek64 = (ImageView) findViewById(R.id.vector_ek64);
		vector_ek65 = (ImageView) findViewById(R.id.vector_ek65);
		vector_ek66 = (ImageView) findViewById(R.id.vector_ek66);
		vector_ek67 = (ImageView) findViewById(R.id.vector_ek67);
		vector_ek68 = (ImageView) findViewById(R.id.vector_ek68);
		vector_ek69 = (ImageView) findViewById(R.id.vector_ek69);
		vector_ek70 = (ImageView) findViewById(R.id.vector_ek70);
		vector_ek71 = (ImageView) findViewById(R.id.vector_ek71);
		vector_ek72 = (ImageView) findViewById(R.id.vector_ek72);
		vector_ek73 = (ImageView) findViewById(R.id.vector_ek73);
		vector_ek74 = (ImageView) findViewById(R.id.vector_ek74);
		vector_ek75 = (ImageView) findViewById(R.id.vector_ek75);
		vector_ek76 = (ImageView) findViewById(R.id.vector_ek76);
		vector_ek77 = (ImageView) findViewById(R.id.vector_ek77);
		vector_ek78 = (ImageView) findViewById(R.id.vector_ek78);
		vector_ek79 = (ImageView) findViewById(R.id.vector_ek79);
		vector_ek80 = (ImageView) findViewById(R.id.vector_ek80);
		vector_ek81 = (ImageView) findViewById(R.id.vector_ek81);
		vector_ek82 = (ImageView) findViewById(R.id.vector_ek82);
		vector_ek83 = (ImageView) findViewById(R.id.vector_ek83);
		vector_ek84 = (ImageView) findViewById(R.id.vector_ek84);
		vector_ek85 = (ImageView) findViewById(R.id.vector_ek85);
		vector_ek86 = (ImageView) findViewById(R.id.vector_ek86);
		vector_ek87 = (ImageView) findViewById(R.id.vector_ek87);
		vector_ek88 = (ImageView) findViewById(R.id.vector_ek88);
		vector_ek89 = (ImageView) findViewById(R.id.vector_ek89);
		vector_ek90 = (ImageView) findViewById(R.id.vector_ek90);
		vector_ek91 = (ImageView) findViewById(R.id.vector_ek91);
		vector_ek92 = (ImageView) findViewById(R.id.vector_ek92);
		vector_ek93 = (ImageView) findViewById(R.id.vector_ek93);
		vector_ek94 = (ImageView) findViewById(R.id.vector_ek94);
		vector_ek95 = (ImageView) findViewById(R.id.vector_ek95);
		vector_ek96 = (ImageView) findViewById(R.id.vector_ek96);
		vector_ek97 = (ImageView) findViewById(R.id.vector_ek97);
		vector_ek98 = (ImageView) findViewById(R.id.vector_ek98);
		vector_ek99 = (ImageView) findViewById(R.id.vector_ek99);
		rectangle_5 = (View) findViewById(R.id.rectangle_5);
		no_color_1 = (ImageView) findViewById(R.id.no_color_1);
		selamat_datang__indira_ = (TextView) findViewById(R.id.selamat_datang__indira_);
		f_o_o_d_n_e_w_s = (TextView) findViewById(R.id.f_o_o_d_n_e_w_s);
		line_1 = (View) findViewById(R.id.line_1);
		line_2 = (View) findViewById(R.id.line_2);
		ellipse_6 = (View) findViewById(R.id.ellipse_6);
		chadfarrel_1 = (ImageView) findViewById(R.id.chadfarrel_1);
		berita_harian_anda_tentang_makanan = (TextView) findViewById(R.id.berita_harian_anda_tentang_makanan);
		news = (View) findViewById(R.id.news);
		_5_sehat_1 = (ImageView) findViewById(R.id._5_sehat_1);
		rectangle_16 = (View) findViewById(R.id.rectangle_16);
		pertajam_kemampuan_otak_dengan_konsumsi_5_makanan_ini_setiap_hari = (TextView) findViewById(R.id.pertajam_kemampuan_otak_dengan_konsumsi_5_makanan_ini_setiap_hari);
		news_ek1 = (View) findViewById(R.id.news_ek1);
		pisang_1 = (ImageView) findViewById(R.id.pisang_1);
		rectangle_16_ek1 = (View) findViewById(R.id.rectangle_16_ek1);
		_5_makanan_sehat_yang_timbulkan_efek_samping_jika_dikonsumsi_berlebihan = (TextView) findViewById(R.id._5_makanan_sehat_yang_timbulkan_efek_samping_jika_dikonsumsi_berlebihan);
		news_ek2 = (View) findViewById(R.id.news_ek2);
		kantuk_1 = (ImageView) findViewById(R.id.kantuk_1);
		rectangle_16_ek2 = (View) findViewById(R.id.rectangle_16_ek2);
		trik_agar_tidak_kantuk_usai_makan_siang = (TextView) findViewById(R.id.trik_agar_tidak_kantuk_usai_makan_siang);
		news_ek3 = (View) findViewById(R.id.news_ek3);
		fermentasi_1 = (ImageView) findViewById(R.id.fermentasi_1);
		rectangle_16_ek3 = (View) findViewById(R.id.rectangle_16_ek3);
		trik_agar_tidak_kantuk_usai_makan_siang_ek1 = (TextView) findViewById(R.id.trik_agar_tidak_kantuk_usai_makan_siang_ek1);
		rectangle_1 = (View) findViewById(R.id.rectangle_1);
		vector_ek100 = (ImageView) findViewById(R.id.vector_ek100);
		vector_ek101 = (ImageView) findViewById(R.id.vector_ek101);
		vector_ek102 = (ImageView) findViewById(R.id.vector_ek102);
		vector_ek103 = (ImageView) findViewById(R.id.vector_ek103);
		vector_ek104 = (ImageView) findViewById(R.id.vector_ek104);
		vector_ek105 = (ImageView) findViewById(R.id.vector_ek105);
		vector_ek106 = (ImageView) findViewById(R.id.vector_ek106);
		vector_ek107 = (ImageView) findViewById(R.id.vector_ek107);
		home_ek1 = (TextView) findViewById(R.id.home_ek1);
	
		
		//custom code goes here
	
	}
}
	
	